<?php
/**
 * @var \Tudn\SystemCategoriesField\Block\Adminhtml\Settings\CategorySelect $block
 */
?>
<div data-bind="scope: 'magento-categories-select'" class="scalable" style="width: 500px">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "magento-categories-select": <?= $block->getJsConfig() ?>
                }
            }
        }
    }
</script>
